name: cloob
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - absl-py=0.15.0=pyhd3eb1b0_0
  - blas=2.113=mkl
  - blas-devel=3.9.0=13_linux64_mkl
  - blinker=1.4=py39h06a4308_0
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2021.10.26=h06a4308_2
  - cachetools=4.2.2=pyhd3eb1b0_0
  - cffi=1.15.0=py39hd667e15_1
  - cryptography=3.4.8=py39hd23ed53_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - dbus=1.13.18=hb2f20db_0
  - expat=2.4.1=h2531618_2
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=h0708190_1
  - ftfy=5.8=py_0
  - glib=2.69.1=h4ff587b_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - google-auth=1.21.3=py_0
  - google-auth-oauthlib=0.4.1=py_2
  - grpcio=1.42.0=py39hce63b2e_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - idna=3.3=pyhd3eb1b0_0
  - importlib-metadata=4.8.2=py39h06a4308_0
  - jbig=2.1=h7f98852_2003
  - jpeg=9e=h7f98852_0
  - kiwisolver=1.3.1=py39h2531618_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=13_linux64_mkl
  - libcblas=3.9.0=13_linux64_mkl
  - libdeflate=1.8=h7f98852_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1d223b6_12
  - libgfortran-ng=11.2.0=h69a702a_12
  - libgfortran5=11.2.0=h5c6108e_12
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=13_linux64_mkl
  - liblapacke=3.9.0=13_linux64_mkl
  - libnsl=2.0.0=h7f98852_0
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.19.1=h4ff587b_0
  - libstdcxx-ng=11.2.0=he4da1e4_12
  - libtiff=4.3.0=h6f004c6_2
  - libuuid=1.0.3=h7f8727e_2
  - libuv=1.43.0=h7f98852_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - libzlib=1.2.11=h36c2ea0_1013
  - llvm-openmp=12.0.1=h4bd325d_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - markdown=3.3.4=py39h06a4308_0
  - matplotlib=3.4.3=py39h06a4308_0
  - matplotlib-base=3.4.3=py39hbbc1b5f_0
  - mkl=2022.0.1=h8d4b97c_803
  - mkl-devel=2022.0.1=ha770c72_804
  - mkl-include=2022.0.1=h8d4b97c_803
  - munkres=1.1.4=py_0
  - ncurses=6.3=h9c3ff4c_0
  - nettle=3.6=he412f7d_0
  - numpy=1.22.1=py39h91f2184_0
  - oauthlib=3.1.1=pyhd3eb1b0_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1m=h7f8727e_0
  - pandas=1.2.4=py39h2531618_0
  - pcre=8.45=h295c915_0
  - pillow=8.4.0=py39ha612740_0
  - pip=22.0.2=pyhd8ed1ab_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.1.0=py39h06a4308_0
  - pyopenssl=21.0.0=pyhd3eb1b0_1
  - pyqt=5.9.2=py39h2531618_6
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.7=h12debd9_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytorch=1.10.2=py3.9_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pytz=2021.3=pyhd3eb1b0_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h46c0cb4_0
  - regex=2021.11.2=py39h7f8727e_0
  - requests=2.27.1=pyhd3eb1b0_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - sip=4.19.13=py39h295c915_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.37.0=h9cd32fc_0
  - tbb=2021.5.0=h4bd325d_0
  - tensorboard=2.6.0=py_1
  - tensorboard-data-server=0.6.0=py39hca6d32c_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tk=8.6.11=h27826a3_1
  - torchaudio=0.10.2=py39_cu113
  - torchvision=0.11.3=py39_cu113
  - tornado=6.1=py39h27cfd23_0
  - tqdm=4.62.3=pyhd3eb1b0_1
  - typing_extensions=4.0.1=pyha770c72_0
  - tzdata=2021e=he74cb21_0
  - urllib3=1.26.8=pyhd3eb1b0_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - werkzeug=2.0.2=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.5=h516909a_1
  - zipp=3.7.0=pyhd3eb1b0_0
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.2=ha95c52a_0
  - pip:
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - argparse==1.4.0
    - asttokens==2.0.5
    - attrs==21.4.0
    - backcall==0.2.0
    - black==22.1.0
    - bleach==4.1.0
    - braceexpand==0.1.7
    - certifi==2021.10.8
    - charset-normalizer==2.0.11
    - click==8.0.3
    - debugpy==1.5.1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - docker-pycreds==0.4.0
    - entrypoints==0.3
    - executing==0.8.2
    - gitdb==4.0.9
    - gitpython==3.1.26
    - ipykernel==6.8.0
    - ipython==8.0.1
    - ipython-genutils==0.2.0
    - jedi==0.18.1
    - jinja2==3.0.3
    - joblib==1.1.0
    - jsonschema==4.4.0
    - jupyter-client==7.1.2
    - jupyter-core==4.9.1
    - jupyterlab-pygments==0.1.2
    - markupsafe==2.0.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - mypy-extensions==0.4.3
    - nbclient==0.5.10
    - nbconvert==6.4.1
    - nbformat==5.1.3
    - nest-asyncio==1.5.4
    - notebook==6.4.8
    - packaging==21.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathspec==0.9.0
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - platformdirs==2.4.1
    - prometheus-client==0.13.1
    - promise==2.3
    - prompt-toolkit==3.0.26
    - protobuf==3.19.4
    - psutil==5.9.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pygments==2.11.2
    - pyparsing==3.0.7
    - pyrsistent==0.18.1
    - pyyaml==6.0
    - pyzmq==22.3.0
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - send2trash==1.8.0
    - sentry-sdk==1.5.4
    - setuptools==59.5.0
    - shortuuid==1.0.8
    - smmap==5.0.0
    - stack-data==0.1.4
    - termcolor==1.1.0
    - terminado==0.13.1
    - testpath==0.5.0
    - threadpoolctl==3.1.0
    - tomli==2.0.0
    - traitlets==5.1.1
    - wandb==0.12.10
    - webencodings==0.5.1
    - yaspin==2.1.0
    - git+https://github.com/ml-jku/hopfield-layers
    - git+https://github.com/tmbdev/webdataset.git
